<a href="https://colab.research.google.com/github/SuperPanww/courses_ML20/blob/master/hw1_panww.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import sys
import pandas as pd
import numpy as np
from google.colab import drive 
!gdown --id '1wNKAxQ29G15kgpBy_asjTcZRRgmsCZRm' --output data.zip
!unzip data.zip
# data = pd.read_csv('gdrive/My Drive/hw1-regression/train.csv', header = None, encoding = 'big5')
data = pd.read_csv('./train.csv', encoding = 'big5')

Downloading...
From: https://drive.google.com/uc?id=1wNKAxQ29G15kgpBy_asjTcZRRgmsCZRm
To: /content/data.zip
100% 177k/177k [00:00<00:00, 52.2MB/s]
Archive:  data.zip
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: test.csv                
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: train.csv               


In [51]:
data.head(18)

日期  測站          測項     0     1  ...    19    20    21    22    23
0   2014/1/1  豐原    AMB_TEMP    14    14  ...    16    15    15    15    15
1   2014/1/1  豐原         CH4   1.8   1.8  ...   1.8   1.8   1.8   1.8   1.8
2   2014/1/1  豐原          CO  0.51  0.41  ...  0.45  0.38  0.35  0.36  0.32
3   2014/1/1  豐原        NMHC   0.2  0.15  ...  0.12   0.1  0.09   0.1  0.08
4   2014/1/1  豐原          NO   0.9   0.6  ...   1.9   1.5   1.6   1.8   1.5
5   2014/1/1  豐原         NO2    16   9.2  ...    12   8.1     7   6.9     6
6   2014/1/1  豐原         NOx    17   9.8  ...    13   9.7   8.6   8.7   7.5
7   2014/1/1  豐原          O3    16    30  ...    34    37    38    38    36
8   2014/1/1  豐原        PM10    56    50  ...    63    46    36    42    42
9   2014/1/1  豐原       PM2.5    26    39  ...    44    41    30    24    13
10  2014/1/1  豐原    RAINFALL    NR    NR  ...    NR    NR    NR    NR    NR
11  2014/1/1  豐原          RH    77    68  ...    69    70    70    70    69
12  2014/1/1  豐原         SO2   1.8     2  ...   2.3     2   1.9   1.9   1.9
13  2014/1/1  豐原         THC     2     2  ...   1.9   1.9   1.9   1.9   1.9
14  2014/1/1  豐原       WD_HR    37    80  ...   121   113   112   106   110
15  2014/1/1  豐原  WIND_DIREC    35    79  ...   118   114   108   102   111
16  2014/1/1  豐原  WIND_SPEED   1.4   1.8  ...     3   2.6   2.7   2.1   2.1
17  2014/1/1  豐原       WS_HR   0.5   0.9  ...   2.5   2.8   2.6   2.4   2.3

[18 rows x 27 columns]

In [0]:
data = data.iloc[:,3:]
data[data == 'NR' ] = 0
raw_data = data.to_numpy()

In [0]:
month_data = {}
for month in range(12):
  sample = np.empty([18,480])
  for day in range(20):
    sample[:,day*24:(day+1)*24] = raw_data[18*(month*20+day):18*(month*20+1+day),:]
  month_data[month] = sample

In [54]:
x = np.empty([12*471,18*9],dtype=float)
y = np.empty([12*471,1],dtype=float)
for month in range(12):
  for day in range(20):
    for hour in range(24):
      if day == 19 and hour > 14:
        continue
      x[month*471+day*24+hour,:] = month_data[month][:,day*24+hour:day*24+hour+9].reshape(1,-1)
      y[month*471+day*24+hour,0] = month_data[month][9,day*24+hour+9]
print(x)
print(y)

[[14.  14.  14.  ...  2.   2.   0.5]
 [14.  14.  13.  ...  2.   0.5  0.3]
 [14.  13.  12.  ...  0.5  0.3  0.8]
 ...
 [17.  18.  19.  ...  1.1  1.4  1.3]
 [18.  19.  18.  ...  1.4  1.3  1.6]
 [19.  18.  17.  ...  1.3  1.6  1.8]]
[[30.]
 [41.]
 [44.]
 ...
 [17.]
 [24.]
 [29.]]


In [0]:
mean_x = np.mean(x,axis=0)
std_x = np.std(x,axis=0)
for i in range(len(x)):
  for j in range(len(x[0])):
    if std_x[j] != 0:
      x[i][j] = (x[i][j] - mean_x[j])/std_x[j]


In [56]:
import math
x_train_set = x[:math.floor(len(x)*0.8),:]
y_train_set = y[:math.floor(len(y)*0.8),:]
x_validation = x[math.floor(len(x)*0.8):,:]
y_validation = y[math.floor(len(x)*0.8):,:]
print(x_train_set)
print(y_train_set)
print(x_validation)
print(y_validation)
print(len(x_train_set))
print(len(y_train_set))
print(len(x_validation))
print(len(y_validation))

[[-1.35825331 -1.35883937 -1.359222   ...  0.26650729  0.2656797
  -1.14082131]
 [-1.35825331 -1.35883937 -1.51819928 ...  0.26650729 -1.13963133
  -1.32832904]
 [-1.35825331 -1.51789368 -1.67717656 ... -1.13923451 -1.32700613
  -0.85955971]
 ...
 [ 0.86929969  0.70886668  0.38952809 ...  1.39110073  0.2656797
  -0.39079039]
 [ 0.71018876  0.39075806  0.07157353 ...  0.26650729 -0.39013211
  -0.39079039]
 [ 0.3919669   0.07264944  0.07157353 ... -0.38950555 -0.39013211
  -0.85955971]]
[[30.]
 [41.]
 [44.]
 ...
 [ 7.]
 [ 5.]
 [14.]]
[[ 0.07374504  0.07264944  0.07157353 ... -0.38950555 -0.85856912
  -0.57829812]
 [ 0.07374504  0.07264944  0.23055081 ... -0.85808615 -0.57750692
   0.54674825]
 [ 0.07374504  0.23170375  0.23055081 ... -0.57693779  0.54674191
  -0.1095288 ]
 ...
 [-0.88092053 -0.72262212 -0.56433559 ... -0.57693779 -0.29644471
  -0.39079039]
 [-0.7218096  -0.56356781 -0.72331287 ... -0.29578943 -0.39013211
  -0.1095288 ]
 [-0.56269867 -0.72262212 -0.88229015 ... -0.3895055

In [57]:
dim = 18*9+1
w = np.zeros([dim,1])
x_set = np.concatenate((np.ones([len(x_train_set),1]),x_train_set),axis = 1).astype(float)
learning_rate = 100
iter_time = 1000
adagrad = np.zeros([dim,1])
eps = 0.0000000001
for i_th in range(iter_time):
  loss = np.square(np.sum(np.power((np.dot(x_set,w) - y_train_set),2))/len(x_train_set))
  if (i_th%100 == 0):
    print(str(i_th)+':'+str(loss))
  gradient = 2 * np.dot(x_set.transpose(),np.dot(x_set,w)-y_train_set)
  adagrad += gradient ** 2
  w = w - learning_rate * gradient / np.sqrt(adagrad + eps)
np.save('weight.npy',w)


0:550557.106856347
100:266647.3476944906
200:11824.048874576361
300:3399.5686402534056
400:2201.5650393179785
500:1805.5464199042285
600:1601.1010199382633
700:1472.2565219837334
800:1383.7500533155865
900:1320.2201532078861


In [61]:
testdata = pd.read_csv('./test.csv',header = None , encoding = 'big5')
test_data = testdata.iloc[:,2:]
test_data[test_data == 'NR'] = 0
test_data = test_data.to_numpy()
test_x = np.empty([240,18*9],dtype = float)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3530: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._where(-key, value, inplace=True)


In [0]:
for i in range(240):
  test_x[i,:] = test_data[i*18:(i+1)*18,:].reshape(1,-1)
for i in range(len(test_x)):
  for j in range(len(test_x[0])):
    if std_x[j] != 0:
      test_x[i][j] = (test_x[i][j] - mean_x[j])/std_x[j]
test_x = np.concatenate((np.ones([240,1]),test_x),axis = 1).astype(float)



In [70]:
w = np.load('weight.npy')
ans_y = np.dot(test_x,w)
ans_y

array([[  7.24908977],
       [ 17.6797687 ],
       [ 24.71103167],
       [  6.36909884],
       [ 28.37337148],
       [ 21.59201636],
       [ 22.83084264],
       [ 31.13537446],
       [ 18.1181207 ],
       [ 57.18105107],
       [ 14.35679576],
       [  9.60412281],
       [ 60.85088529],
       [ 51.31564299],
       [ 20.84716299],
       [ 11.91858833],
       [ 31.91703121],
       [ 67.45559414],
       [ -0.63215684],
       [ 16.72799379],
       [ 42.21696344],
       [ 71.65542095],
       [  9.8820184 ],
       [ 18.42548231],
       [ 15.14857367],
       [ 38.25844015],
       [ 14.10444923],
       [ 75.101792  ],
       [  7.79514917],
       [ 54.88896792],
       [ 22.2796469 ],
       [  8.70958679],
       [  4.41551641],
       [ 22.80232325],
       [ 31.20428127],
       [ 37.0358169 ],
       [ 43.04019035],
       [ 30.2586288 ],
       [ 42.47478835],
       [ 35.9853158 ],
       [  6.45215654],
       [ 40.68484196],
       [ 32.61868857],
       [ 50

In [72]:
import csv
with open('submit.csv',mode='w',newline='') as submit_file:
  csv_writer = csv.writer(submit_file)
  header = ['id','value']
  print(header)
  csv_writer.writerow(header)
  for i in range(240):
    row = ['id_'+str(i),ans_y[i][0]]
    csv_writer.writerow(row)
    print(row)

['id', 'value']
['id_0', 7.24908976826053]
['id_1', 17.679768702689703]
['id_2', 24.711031667711502]
['id_3', 6.369098836970052]
['id_4', 28.37337148373313]
['id_5', 21.592016362479523]
['id_6', 22.83084263660065]
['id_7', 31.135374457500454]
['id_8', 18.1181206972825]
['id_9', 57.18105107311822]
['id_10', 14.356795756894032]
['id_11', 9.604122812579146]
['id_12', 60.850885289488325]
['id_13', 51.31564298738868]
['id_14', 20.847162985390046]
['id_15', 11.918588326918641]
['id_16', 31.91703120750646]
['id_17', 67.45559413525699]
['id_18', -0.63215683717406]
['id_19', 16.727993788780747]
['id_20', 42.21696344117317]
['id_21', 71.65542095380836]
['id_22', 9.882018398554546]
['id_23', 18.425482306666133]
['id_24', 15.148573673067972]
['id_25', 38.25844014988791]
['id_26', 14.104449231390827]
['id_27', 75.1017919955949]
['id_28', 7.79514916660021]
['id_29', 54.88896791759236]
['id_30', 22.279646897828602]
['id_31', 8.70958678911192]
['id_32', 4.4155164135662535]
['id_33', 22.802323251380162